# Generated by Django 4.1.3 on 2022-11-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_publishing_house'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author_id'], 'verbose_name_plural': 'Book'},
        ),
    ]
