# Generated by Django 4.1.3 on 2022-12-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_options_alter_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amount_page',
            field=models.IntegerField(default=0),
        ),
    ]
